import React from "react";

export const routes = [
  {
    to: null,
    title: "Creación de componentes",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem1",
    title: "Componente usando clases",
    description: "Muestra como crear un componente usando clases. Obsoleto.",
    component: React.lazy(() => import("../pages/Ejem1")),
  },
  {
    to: "Ejem2",
    title: "Componente usando funciones simples",
    description: "Muestra como crear un componente usando funciones clasicas.",
    component: React.lazy(() => import("../pages/Ejem2")),
  },
  {
    to: "Ejem3",
    title: "Componente usando funciones tipo flecha",
    description: "Muestra como crear un componente usando funciones de tipo flecha.",
    component: React.lazy(() => import("../pages/Ejem3")),
  },
  {
    to: "Ejem4",
    title: "Componente condicionales",
    description: "Muestra como codiciones en react",
    component: React.lazy(() => import("../pages/Ejem4")),
  },

  {
    to: null,
    title: "Props",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem5",
    title: "Pasar props a un componente",
    description: "Muestra se pueden pasar valores a un compoenente",
    component: React.lazy(() => import("../pages/Ejem5")),
  },
  {
    to: "Ejem6",
    title: "Estilado de compoentes",
    description: "Como dar formato a los componentes, introducción",
    component: React.lazy(() => import("../pages/Ejem6")),
  },
  {
    to: "Ejem7",
    title: "Pasando funciones como props",
    description: "Uso de funciones en las props",
    component: React.lazy(() => import("../pages/Ejem7")),
  },
  {
    to: "Ejem8",
    title: "Modificación de las props de forma incorrecta",
    description: "Las propos son inmutables",
    component: React.lazy(() => import("../pages/Ejem8")),
  },
  {
    to: "Ejem9",
    title: "Children",
    description: "Pasar propiedes por el children",
    component: React.lazy(() => import("../pages/Ejem9")),
  },
  {
    to: "Ejercicio0",
    title: "Pasar de grados a farengeith",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio0")),
  },
  {
    to: "Ejercicio1",
    title: "Card personalizado",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio1")),
  },
  {
    to: "Ejercicio2",
    title: "Calculadora",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio2")),
  },
  {
    to: "Ejem10",
    title: "Eventos",
    description: "Manejo de eventos en react",
    component: React.lazy(() => import("../pages/Ejem10")),
  },
  {
    to: null,
    title: "Manejo del estado",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem11",
    title: "Manejo del estado",
    description: "Muestra como manejar el estado en react",
    component: React.lazy(() => import("../pages/Ejem11")),
  },

  {
    to: "Ejercicio3",
    title: "Ejercicio3",
    description: "Mostrar y ocultar texto",
    component: React.lazy(() => import("../pages/Ejercicio3")),
  },
  {
    to: "Ejem12",
    title: "Manejo del estado 2",
    description: "Como se renderiza el componente",
    component: React.lazy(() => import("../pages/Ejem12")),
  },
  {
    to: "Ejem13",
    title: "Propagación del estado",
    description: "El estado se propaga a los hijos",
    component: React.lazy(() => import("../pages/Ejem13")),
  },
  {
    to: "Ejercicio4",
    title: "Ejercicio4",
    description: "Lanzamiento de un dado",
    component: React.lazy(() => import("../pages/Ejercicio4")),
  },
  {
    to: "Ejercicio5",
    title: "Ejercicio5",
    description: "Crea un componente boton",
    component: React.lazy(() => import("../pages/Ejercicio5")),
  },
  {
    to: "Ejem14",
    title: "Inicialización del estado",
    description: "Muestro como se inicializa el estado",
    component: React.lazy(() => import("../pages/Ejem14")),
  },
  {
    to: "Ejem15",
    title: "Mostrar varios elementos",
    description: "Usamos el map para mostrar varios elementos",
    component: React.lazy(() => import("../pages/Ejem15")),
  },
  {
    to: "Ejercicio6",
    title: "Ejercicio 6:",
    description: "Seleccionar elemento de una lista",
    component: React.lazy(() => import("../pages/Ejercicio6")),
  },
  {
    to: null,
    title: "Efectos",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem16",
    title: "Ciclo de vida",
    description: "Uso del hook useEffect",
    component: React.lazy(() => import("../pages/Ejem16")),
  },
  {
    to: "Ejem17",
    title: "Ciclo de vida",
    description: "Desmontar el estado",
    component: React.lazy(() => import("../pages/Ejem17")),
  },
  {
    to: "Ejem18",
    title: "Conectandome a apis",
    description: "Obteniendo lista de pokemons",
    component: React.lazy(() => import("../pages/Ejem18")),
  },
  {
    to: "Ejem19",
    title: "Conectandome a apis promiseAll",
    description: "Obteniendo lista de pokemons con foto",
    component: React.lazy(() => import("../pages/Ejem19")),
  },
  {
    to: "Ejem20",
    title: "Eventos de teclado",
    description: "Capturar eventos de teclado",
    component: React.lazy(() => import("../pages/Ejem20")),
  },
  {
    to: "Ejercicio7",
    title: "Ejercicio 7:",
    description: "Bitcoins",
    component: React.lazy(() => import("../pages/Ejercicio7")),
  },
  {
    to: "Ejem21",
    title: "Problemas con el useEffect",
    description: "Bucles infinitos",
    component: React.lazy(() => import("../pages/Ejem21")),
  },
  {
    to: null,
    title: "Formularios",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem22",
    title: "Formulario simples",
    description: "Control de formularios",
    component: React.lazy(() => import("../pages/Ejem22")),
  },
  {
    to: "Ejem23",
    title: "Formulario con campues multiples",
    description: "Control de formularios",
    component: React.lazy(() => import("../pages/Ejem23")),
  },
  {
    to: "Ejem24",
    title: "Hooks personalizados",
    description: "Crear nuestros propios hooks para simplificar código",
    component: React.lazy(() => import("../pages/Ejem24")),
  },
  {
    to: "Ejercicio8",
    title: "Ejercicio 8:",
    description: "Formulario",
    component: React.lazy(() => import("../pages/Ejercicio8")),
  },
  {
    to: "Ejercicio11",
    title: "Ejercicio 11:",
    description: "Formulario con hooks y generics",
    component: React.lazy(() => import("../pages/Ejercicio11")),
  },
];
